# Site settings
title: "Nafis Fuad"
name: "Nafis Fuad"
email: "nafisfuad@wayne.edu"
description: "PhD Researcher| Ai in Transportation | LLM Engineer | Data Science | Machine Learning"
url: "https://nafis-saad.github.io"
baseurl: ""

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: /page:num/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Sidebar information
author:
  name   : "Nafis Fuad"
  avatar : "/images/profile.jpg"
  bio    : "Short biography for the left-hand sidebar"
  location: "USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your_email@example.com"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nafis-saad"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nafis-saad"
