# ===========================================================
#   AcademicPages Configuration — customized for Nafis Fuad
# ===========================================================

locale                   : "en-US"
title                    : "Nafis Fuad"
title_separator          : "-"
name                     : &name "Nafis Fuad"
description              : &description "Ph.D. Researcher | Data Science | Machine Learning"
keywords                 : "data science, machine learning, research, academia, portfolio"
url                      : "https://nafis-saad.github.io"   # main GitHub Pages URL
baseurl                  : ""                               # no subpath
repository               : "nafis-saad/nafis_fuad.github.io"
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

# -----------------------------------------------------------
# Comments (disabled for now)
# -----------------------------------------------------------
comments:
  provider               : false

# -----------------------------------------------------------
# SEO + Social Verification
# -----------------------------------------------------------
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# -----------------------------------------------------------
# Social Sharing
# -----------------------------------------------------------
twitter:
  username               : &twitter nafis_fuad
facebook:
  username               :
og_image                 :

social:
  type                   : Person
  name                   : "Nafis Fuad"
  links:
    - "https://github.com/nafis-saad"
    - "https://www.linkedin.com/in/nafis-fuad/"
    - "https://scholar.google.com/"
    - "mailto:nafis.fuad@example.com"

# -----------------------------------------------------------
# Analytics (optional)
# -----------------------------------------------------------
analytics:
  provider               : false
  google:
    tracking_id          :

# -----------------------------------------------------------
# Site Author
# -----------------------------------------------------------
author:
  name             : "Nafis Fuad"
  avatar           : "profile.jpg"      # put your image in /images/
  bio              : "Ph.D. Researcher | Data Science | Machine Learning | AI for Sustainability"
  location         : "United States"
  googlescholar    : "https://scholar.google.com/"
  researchgate     :
  email            : "nafis.fuad@example.com"
  github           : "nafis-saad"
  linkedin         : "nafis-fuad"
  twitter          : "nafis_fuad"

# -----------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6

# -----------------------------------------------------------
# Collections
# -----------------------------------------------------------
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# -----------------------------------------------------------
# Defaults
# -----------------------------------------------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# -----------------------------------------------------------
# Sass / Theme / Plugins
# -----------------------------------------------------------
sass:
  sass_dir: _sass
  style: compressed

theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

# mimic GitHub Pages safe mode
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# -----------------------------------------------------------
# Archives
# -----------------------------------------------------------
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# -----------------------------------------------------------
# Output / Pagination
# -----------------------------------------------------------
permalink: /:categories/:title/
timezone: America/New_York

# -----------------------------------------------------------
# HTML Compression
# -----------------------------------------------------------
compress_html:
  clippings: all
  ignore:
    envs: development
